version: '3.9'
services:
  caddy:
    image: caddy
    container_name: caddy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./data/caddy:/data
    environment:
      - ACME_AGREE=true
      - ACME_CA=https://acme-v02.api.letsencrypt.org/directory
      - ACME_EMAIL=${ACME_EMAIL}
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV:-production}
        PORT: ${PORT:-3000}
    env_file:
      - .env
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
  ai-server:
    image: gosua/recommend-ai:1.0.1
    ports:
      - '8010:8010'
