name: Deploy to EC2 on main

on:
  push:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: deploy-ec2-main
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH and Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          request_pty: true
          script_stop: true
          script: |
            set -e
            if [ -z "${{ secrets.EC2_PATH }}" ]; then
              echo "Missing required secret: EC2_PATH" >&2
              exit 1
            fi

            # Elevate to root login shell and run all commands from there
            sudo -i bash -lc '
              set -e
              REPO_DIR="${{ secrets.EC2_PATH }}"
              REPO_URL="${{ secrets.EC2_REPO_SSH }}" # e.g., git@github.com:owner/BabMukDang-Socket.git

              mkdir -p "$REPO_DIR"
              cd "$REPO_DIR"

              # First-time bootstrap if the repo is not present
              if [ ! -d .git ]; then
                if [ -z "$REPO_URL" ]; then
                  echo "Repository not found at $REPO_DIR and EC2_REPO_SSH is not set. Set EC2_REPO_SSH to SSH URL (e.g., git@github.com:owner/BabMukDang-Socket.git)." >&2
                  exit 1
                fi
                mkdir -p ~/.ssh
                ssh-keyscan -H github.com >> ~/.ssh/known_hosts 2>/dev/null || true
                git clone "$REPO_URL" .
              fi

              git fetch --all --prune
              git checkout main
              git reset --hard origin/main
              # Ensure latest images and rebuild containers (supports both v1 and v2 compose)
              if docker compose version >/dev/null 2>&1; then DC="docker compose"; else DC="docker-compose"; fi
              $DC pull || true
              $DC up --build -d
              # Optional cleanup (non-fatal)
              docker system prune -f || true
            '
