name: Deploy to EC2 on main

on:
  push:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: deploy-ec2-main
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH and Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            set -e
            cd "${{ secrets.EC2_PATH }}"
            git fetch --all --prune
            git checkout main
            git reset --hard origin/main
            # Ensure latest images and rebuild containers (supports both v1 and v2 compose)
            if docker compose version >/dev/null 2>&1; then DC="docker compose"; else DC="docker-compose"; fi
            $DC pull || true
            $DC up --build -d
            # Optional cleanup (non-fatal)
            docker system prune -f || true
